name: "releasenote generator"
description: "bash releasenote generator for keepachangelog format"
inputs:
  version:
    description: "version to get from changelog"
    required: true
    default: "latest"
  changelog:
    description: "changelog file"
    required: true
    default: "CHANGELOG.md"
  releasenotes:
    description: "release notes file"
    required: true
    default: "RELEASENOTES.md"

outputs:
  releasenotes:
    description: "release notes as a string"
    value: ${{ steps.read.outputs.content }}

runs:
  using: "composite"
  steps:
    - name: generate release notes
      shell: bash
      run: bash ${{ github.action_path }}/releasenote-gen.sh "${{ inputs.version }}" "${{ inputs.changelog }}" "${{ inputs.releasenotes }}"

    - name: read release notes
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: "${{ inputs.releasenotes }}"
