name: "releasenote generator"
description: "bash releasenote generator for keepachangelog format"
inputs:
  version:
    description: "version to get from changelog"
    required: true
    default: "latest"
  changelog:
    description: "changelog file"
    required: true
    default: "CHANGELOG.md"
  releasenotes:
    description: "release notes file"
    required: true
    default: "RELEASENOTES.md"

outputs:
  releasenotes:
    description: "release notes as a string"
    value: ${{ steps.read.outputs.releasenotes }}

runs:
  using: "composite"
  steps:
    - name: generate release notes
      id: generate
      shell: bash
      run: bash ${{ github.action_path }}/releasenote-gen.sh "${{ inputs.version }}" "${{ inputs.changelog }}" "${{ inputs.releasenotes }}"

    - name: set output
      id: read
      shell: bash
      run: echo 'releasenotes << EOF' >> ${GITHUB_OUTPUT}; cat <<< "$(< "${{ inputs.releasenotes }}")" >> ${GITHUB_OUTPUT}; echo 'EOF' >> ${GITHUB_OUTPUT}
